################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/all/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/collection/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "npm"
    directory: "/youtube/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
